### ISSUE TITLE
portstat didn't work in crontab

### ISSUE THREAD

**Issue by imlonghao** [imlonghao/portstat#1]
I run portstat in crontab but it didn't work, here is the log from the mail to the root

```
Message 1:
From root@imlonghao.com  Thu Jun 18 17:17:02 2015
Date: Thu, 18 Jun 2015 17:17:01 +0800
From: root@imlonghao.com (Cron Daemon)
To: root@imlonghao.com
Subject: Cron <root@imlonghao> /usr/bin/python /root/a.py -u
Content-Type: text/plain; charset=ANSI_X3.4-1968
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>

sh: 1: iptables: not found
Traceback (most recent call last):
  File "/root/a.py", line 113, in <module>
    main()
  File "/root/a.py", line 109, in main
    upload(portGroups)
  File "/root/a.py", line 80, in upload
    line[i] = stats[i]
KeyError: 9999

```

**Comment by imlonghao** [comment]
As we can see that the main reason is the iptables path missing

```
sh: 1: iptables: not found
```

In crontab environment, all the command should be in the absolutely path.
